#!/bin/sh /etc/rc.common
#
# Copyright (C) 2021 Mmx
#
# This is free software, licensed under the GNU Affero General Public License v3.
# See /LICENSE for more information.
#

START=99
STOP=15

SERVICE_DAEMONIZE=1
NAME=BitSrunLogin

start(){
    /usr/bin/BitSrunLoginGo --config=/etc/config/BitSrunLoginGo.json --daemon
}

stop() {
    killall -q BitSrunLoginGo
}
